version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "dev2-sql"
    ports:
      - "1433:1433"
    volumes:
      - ./docker-data/mssql:/var/opt/data
    environment:
      MSSQL_SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AI"